{% set name = "torch-scatter" %}
{% set version = "2.0.9" %}
# see github.com/conda-forge/conda-forge.github.io/issues/1059 for naming discussion
{% set torch_proc_type = "cuda" if cuda_compiler_version != "None" else "cpu" %}



package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/torch_scatter-{{ version }}.tar.gz
  sha256: 08f5511d64473badf0a71d156b36dc2b09b9c2f00a7cd373b935b490c477a7f1

build:
  number: 4
  rpaths:
    - lib/
    - {{ SP_DIR }}/torch/lib
  missing_dso_whitelist:
    - '*/libcuda.*'  # [linux64 or ppc64le]
  skip: true  # [win]
  skip: true  # [cuda_compiler_version == "10.2"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [cuda_compiler_version != "None"]
    # https://conda-forge.org/docs/maintainer/knowledge_base.html?highlight=cuda#using-centos-7
    - sysroot_linux-64 2.17  # [linux64]
  host:
    - cudnn                           # [cuda_compiler_version != "None"]
    - nccl                            # [cuda_compiler_version != "None"]
    - pip
    - pytest-runner
    - python
    - pytorch
    - pytorch =*={{ torch_proc_type }}*
    - numpy
    - tqdm
    - scipy
    - networkx
    - scikit-learn
    - requests
    - pandas
    - rdflib
    - googledrivedownloader
    - jinja2
    - pyparsing
  run:
    - python
    - {{ pin_compatible('cudnn') }}  # [cuda_compiler_version != "None"]
    - {{ pin_compatible('numpy') }}
  run_constrained:
    # 2022/02/05 hmaarrfk
    # While conda packaging seems to allow us to specify
    # constraints on the same package in different lines
    # the resulting package doesn't have the ability to
    # be specified in multiples lines
    # This makes it tricky to use run_exports
    # we add the GPU constraint in the run_constrained
    # to allow us to have "two" constraints on the
    # running package
    - pytorch =*={{ torch_proc_type }}*

test:
  imports:
    - torch_scatter
    - torch_scatter.composite
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/rusty1s/pytorch_scatter
  summary: PyTorch Extension Library of Optimized Scatter Operations
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sarthakpati
