conda_forge_output_validation: true
# Ensure compatibility with pytorch. They need cos7
os_version:
  linux_64: cos7
bot:
  automerge: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
